### ISSUE TITLE
Noise Amplitude Calculation

### ISSUE THREAD

**Issue by garverp** [radioML/dataset#10]
I think the noise amplitude calculation should be:
10^(-snr_db/20.0), but the code has: 10^(-snr_db/10.0)

It looks like all the transmitters scale to an average magnitude squared P_avg=1. Then SNR_lin = P_avg/sigma^2, so sigma^2 = 1/snr_lin = 1/(10^(-snr_db/10)) => sigma = sqrt(1/(10^(-snr_db/10))) = 10^(-snr_db/20). The dynamic channel model takes in the standard deviation not the variance.

What am I missing?

**Comment by osh** [comment]
In newer versions we clearly us Es/N0, this will be released soon

**Comment by garverp** [comment]
OK, but does that mean the results will change from previously published papers using this code?
