### ISSUE TITLE
No module named mapper

### ISSUE THREAD

**Issue by cjam** [radioML/dataset#11]
Hey guys,

I'm trying to run the dataset generation tools from outside of the docker environment that you have setup I am getting an error in the transmitters.py:

`ImportError: No module named mapper`

I presume there is a dependency that I'm missing here.  I noticed in the docker environment / build_dataset script that your running a setup_env.sh which I presume is adding some paths to the python path for execution.

Thanks for any help

**Comment by garverp** [comment]
gr-mapper [1], I think you can install it with pyBOMBS.


[1] https://github.com/gr-vt/gr-mapper

**Comment by rjzak** [comment]
I had the same issue. Gotta love the total lack of documentation with this project.

**Comment by n-west** [comment]
@rjzak Paul provided a link to the repo where you can download gr-mapper...

**Comment by kevinbdsouza** [comment]
I'm having an issue with mapper installation. How do I install mapper with pybombs or from git repo on MacOS? Any help is appreciated. Thanks

**Comment by n-west** [comment]
Mapper is gr-mapper.

**Comment by kevinbdsouza** [comment]
Sorry was referring to gr-mapper itself. Followed instructions at https://github.com/radioML/dataset/issues/13 but didn't work on Mac.
