### ISSUE TITLE
ImportError: No module named mediatools

### ISSUE THREAD

**Issue by er-mao** [radioML/dataset#12]
Sorry, when I tried to run the generate_RML2016.10a.py, this error came out. Could you please give me a hand? 

Traceback (most recent call last):
  File "e:\python\dataset_master\generate_RML2016.10a.py", line 3, in <module>
    from source_alphabet import source_alphabet
  File "e:\python\dataset_master\source_alphabet.py", line 3, in <module>
    import mediatools
ImportError: No module named mediatools

**Comment by er-mao** [comment]
Maybe it's this:
[https://moo.cmcl.cs.cmu.edu/trac/cgran/wiki/mediatools](url)

**Comment by ghost** [comment]
Same Problem...

**Comment by osh** [comment]
https://github.com/osh/gr-mediatools

**Comment by pachpandepriti** [comment]
Please let me know how u solved this

**Comment by n-west** [comment]
You install gr-mediatools

**Comment by pachpandepriti** [comment]
It's giving me error I tried using cmake. but nothing worked

**Comment by LlewellynS96** [comment]
@pachpandepriti sudo apt-get install libavcodec-dev libavformat-dev

**Comment by SYTo7436** [comment]
现在解决了吗？
