### ISSUE TITLE
Can't find mediatools package

### ISSUE THREAD

**Issue by yonidavidson** [radioML/dataset#6]
I am trying to build the datasets but "import mediatools" fails.
I tried to install manually gr-mediatools but It doesn't work.

**Comment by osh** [comment]
this can be installed in pybombs via 'pybombs install gr-mediatools'
or built manually from https://github.com/osh/gr-mediatools

**Comment by Ostnie** [comment]
when I use pybombs install gr-mediatools  I get
[INFO] Prefix Python version is: 2.7.12
[INFO] PyBOMBS Version 2.3.4a0
[INFO] Install python-apt to speed up apt processing.
[INFO] Phase 1: Creating install tree and installing binary packages:
[INFO] No packages to install.

but I still can't import mediatools
