### ISSUE TITLE
error decoding file

### ISSUE THREAD

**Issue by ziyuanjun** [radioML/dataset#9]
When I run generate_RML2016.10a.py, this error come out: 

> $ ./generate_RML2016.10a.py 
> snr is  -20
> len(interp_taps) = 287
> [mp3 @ 0x7fcfb8000b60] Skipping 0 bytes of junk at 70700.
> [mp3 @ 0x7fcfb8002040] Header missing
> error decoding file
> ...
> error decoding file
> WARN: fractional_interpolator is deprecated. Please use fractional_resampler instead.
> [mp3 @ 0x7fcff0000b60] Skipping 0 bytes of junk at 70700.
> [mp3 @ 0x7fcff0096c80] Header missing
> error decoding file
> all done. writing to disk

Is there something that my computer missed? 

By the way, it seems that the `RML2016.10a_dict.dat` has also been generated successfully. The .dat file size is 640.9MB.

**Comment by hongdehua** [comment]
Traceback (most recent call last):
  File "D:\Program Files (x86)\gnuradio\lib\site-packages\gnuradio\gr\__init__.py", line 37, in <module>
    from runtime_swig import *
ImportError: No module named 'runtime_swig'

When I run generate_RML2016.10a.py, this error is above.
Is there something about GNU that I need install?

您好，想咨询一下您，为什么我这边直接运行这个文件夹的代码，会一直提醒少各种库呢？是不是哪里还有一个GNU的库需要安装？

**Comment by ziyuanjun** [comment]
The error is related to SWIG, you can try to install it alone. 
And maybe your GNU Radio has not been installed correctly. I use GNU Radio in linux,  I'm not sure whether Win is a good choice.

**Comment by wtarp** [comment]
I'm having the same problem.
It feels like there's something wrong with libav.
I have tried to reinstall gr-mediatools, but the problem still exists.

**Comment by JinzhiLin** [comment]
@ziyuanjun I'm having the same problem, have you solve this issue?
I have not got RML2016.10a_dict.dat generated. A "Segmentation fault" error is encounted!

> error decoding file
gr::log :WARN: fractional_interpolator_ff1 - fractional_interpolator is deprecated. Please use fractional_resampler instead.
[mp3 @ 0x7fc284133f60] Skipping 0 bytes of junk at 70700.
[mp3 @ 0x7fc284c72a60] Header missing
error decoding file
gr::log :WARN: fractional_interpolator_ff0 - fractional_interpolator is deprecated. Please use fractional_resampler instead.
[mp3 @ 0x7fc2a8132ca0] Skipping 0 bytes of junk at 70700.
[mp3 @ 0x7fc2a8070840] Header missing
error decoding file
all done. writing to disk
Segmentation fault (core dumped)

**Comment by osh** [comment]
this is a gnu radio problem

**Comment by pachpandepriti** [comment]
Can you mention the steps you followed to install gr mediatools? I am not able to do that.

**Comment by LlewellynS96** [comment]
@osh how can this issue be solved? Is the issue related to gr-mediatools?

**Comment by juanjuanhuang** [comment]
> The error is related to SWIG, you can try to install it alone.
> And maybe your GNU Radio has not been installed correctly. I use GNU Radio in linux, I'm not sure whether Win is a good choice.

Using pybombs install SWIG???

**Comment by venkateshsathya** [comment]
> Can you mention the steps you followed to install gr mediatools? I am not able to do that.

I followed two steps in here and fixed the issue:

sudo apt-get install libavcodec-dev libavformat-dev

followed by making the change mentioned in the link below... 
https://stackoverflow.com/questions/43432797/failed-to-make-when-installing-gr-mediatools/43588739#43588739?newreg=593b7b86e1614e79bdd556a20f9e889c
